[workspace]
members = [
	"service",
	"config",
	"memory",
	"engine/preprocessor",
	"engine/translator",
]
default-members = ["service"]
resolver = "2"

[workspace.package]
repository = "https://github.com/fodydev/afrim"
license = "MPL-2.0"
authors = ["Brady Fomegne <brady.fomegne@outlook.com>"]

