[toolchain]
channel = "1.87"
components = ["cargo", "rustfmt", "clippy"]
targets = [
    "x86_64-unknown-linux-gnu",   # Linux
    "x86_64-apple-darwin",        # macOS
    "x86_64-pc-windows-msvc"      # Windows (MSVC)
]
