#![deny(missing_docs)]

/// Possible commands that can be generated by the `afrim-preprocessor`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Command {
    /// Request to commit a text.
    CommitText(String),
    /// Request to pause the listener.
    Pause,
    /// Request to resume the listener.
    Resume,
    /// Request to delete the last character.
    Delete,
    /// Request to clean the previous delete operation.
    ///
    /// Useful by example in case that a key has been pressed, and we want to ensure
    /// that it has been released before continuing.
    CleanDelete,
}
